"""handle-quiz-attempt.

Revision ID: 212c85530e1f
Revises: 6479de0ccd20
Create Date: 2025-05-21 12:45:01.886940

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '212c85530e1f'
down_revision: str | None = '6479de0ccd20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handle_quiz_attempt',
    sa.Column('id_handle_quiz_attempt', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('id_quiz_attempt', sa.Integer(), nullable=False, comment='FK → QuizAttempt'),
    sa.Column('handled', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Handled flag'),
    sa.ForeignKeyConstraint(['id_quiz_attempt'], ['quiz_attempt.id_quiz_attempt'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_handle_quiz_attempt')
    )
    op.create_index(op.f('ix_handle_quiz_attempt_id_handle_quiz_attempt'), 'handle_quiz_attempt', ['id_handle_quiz_attempt'], unique=False)
    op.create_index(op.f('ix_handle_quiz_attempt_id_quiz_attempt'), 'handle_quiz_attempt', ['id_quiz_attempt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handle_quiz_attempt_id_quiz_attempt'), table_name='handle_quiz_attempt')
    op.drop_index(op.f('ix_handle_quiz_attempt_id_handle_quiz_attempt'), table_name='handle_quiz_attempt')
    op.drop_table('handle_quiz_attempt')
    # ### end Alembic commands ###
