"""quiz-attempt-answers.

Revision ID: 6479de0ccd20
Revises: 699d0ba936fc
Create Date: 2025-04-27 15:54:14.607165

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6479de0ccd20'
down_revision: str | None = '699d0ba936fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempt_answer',
    sa.Column('id_quiz_attempt_answer', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('id_quiz_attempt', sa.Integer(), nullable=False, comment='FK → QuizAttempt'),
    sa.Column('id_question', sa.Integer(), nullable=False, comment='FK → Question'),
    sa.Column('id_answer_option', sa.Integer(), nullable=False, comment='FK → AnswerOption'),
    sa.ForeignKeyConstraint(['id_answer_option'], ['answer_option.id_answer_option'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_question'], ['question.id_question'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_quiz_attempt'], ['quiz_attempt.id_quiz_attempt'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_quiz_attempt_answer')
    )
    op.create_index(op.f('ix_quiz_attempt_answer_id_answer_option'), 'quiz_attempt_answer', ['id_answer_option'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_answer_id_question'), 'quiz_attempt_answer', ['id_question'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_answer_id_quiz_attempt'), 'quiz_attempt_answer', ['id_quiz_attempt'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_answer_id_quiz_attempt_answer'), 'quiz_attempt_answer', ['id_quiz_attempt_answer'], unique=False)
    op.drop_column('quiz_attempt', 'correct_answers')
    op.drop_column('quiz_attempt', 'total_answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempt', sa.Column('total_answers', sa.INTEGER(), autoincrement=False, nullable=False, comment='Count of total answers'))
    op.add_column('quiz_attempt', sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=False, comment='Count of correct answers'))
    op.drop_index(op.f('ix_quiz_attempt_answer_id_quiz_attempt_answer'), table_name='quiz_attempt_answer')
    op.drop_index(op.f('ix_quiz_attempt_answer_id_quiz_attempt'), table_name='quiz_attempt_answer')
    op.drop_index(op.f('ix_quiz_attempt_answer_id_question'), table_name='quiz_attempt_answer')
    op.drop_index(op.f('ix_quiz_attempt_answer_id_answer_option'), table_name='quiz_attempt_answer')
    op.drop_table('quiz_attempt_answer')
    # ### end Alembic commands ###
