"""file.

Revision ID: 1257a9edfbd1
Revises: 212c85530e1f
Create Date: 2025-05-21 15:38:21.156349

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1257a9edfbd1'
down_revision: str | None = '212c85530e1f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id_file', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Stored filename'),
    sa.Column('id_course', sa.Integer(), nullable=False, comment='FK → Course'),
    sa.ForeignKeyConstraint(['id_course'], ['course.id_course'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_file')
    )
    op.create_index(op.f('ix_file_id_course'), 'file', ['id_course'], unique=False)
    op.create_index(op.f('ix_file_id_file'), 'file', ['id_file'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_id_file'), table_name='file')
    op.drop_index(op.f('ix_file_id_course'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
