"""main-models-generated.

Revision ID: 699d0ba936fc
Revises: dddff7f59bd1
Create Date: 2025-04-26 15:40:47.207587

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '699d0ba936fc'
down_revision: str | None = 'dddff7f59bd1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('first_name', sa.String(length=255), nullable=True, comment='First name'),
    sa.Column('second_name', sa.String(length=255), nullable=True, comment='Second name'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Username'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password'),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id_user'), 'user', ['id_user'], unique=False)
    op.create_table('course',
    sa.Column('id_course', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Course title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Course description'),
    sa.Column('id_user', sa.Integer(), nullable=False, comment='FK → User (owner)'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_course')
    )
    op.create_index(op.f('ix_course_id_course'), 'course', ['id_course'], unique=False)
    op.create_index(op.f('ix_course_id_user'), 'course', ['id_user'], unique=False)
    op.create_table('course_member',
    sa.Column('id_course_member', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('id_course', sa.Integer(), nullable=False, comment='FK → Course'),
    sa.Column('id_user', sa.Integer(), nullable=False, comment='FK → User'),
    sa.ForeignKeyConstraint(['id_course'], ['course.id_course'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_course_member')
    )
    op.create_index(op.f('ix_course_member_id_course'), 'course_member', ['id_course'], unique=False)
    op.create_index(op.f('ix_course_member_id_course_member'), 'course_member', ['id_course_member'], unique=False)
    op.create_index(op.f('ix_course_member_id_user'), 'course_member', ['id_user'], unique=False)
    op.create_table('quiz',
    sa.Column('id_quiz', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('id_course', sa.Integer(), nullable=False, comment='FK → Course'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Quiz title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Quiz description'),
    sa.Column('coins', sa.Integer(), nullable=False, comment='Reward coins'),
    sa.Column('min_correct_ratio', sa.Float(), nullable=False, comment='Minimum correct‐answer ratio'),
    sa.ForeignKeyConstraint(['id_course'], ['course.id_course'], ),
    sa.PrimaryKeyConstraint('id_quiz')
    )
    op.create_index(op.f('ix_quiz_id_course'), 'quiz', ['id_course'], unique=False)
    op.create_index(op.f('ix_quiz_id_quiz'), 'quiz', ['id_quiz'], unique=False)
    op.create_table('question',
    sa.Column('id_question', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('id_quiz', sa.Integer(), nullable=False, comment='FK → Quiz'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Question title'),
    sa.Column('text', sa.Text(), nullable=False, comment='Question text'),
    sa.Column('study_materials', sa.Text(), nullable=True, comment='Supplemental materials'),
    sa.ForeignKeyConstraint(['id_quiz'], ['quiz.id_quiz'], ),
    sa.PrimaryKeyConstraint('id_question')
    )
    op.create_index(op.f('ix_question_id_question'), 'question', ['id_question'], unique=False)
    op.create_index(op.f('ix_question_id_quiz'), 'question', ['id_quiz'], unique=False)
    op.create_table('quiz_attempt',
    sa.Column('id_quiz_attempt', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('id_quiz', sa.Integer(), nullable=False, comment='FK → Quiz'),
    sa.Column('id_user', sa.Integer(), nullable=False, comment='FK → User'),
    sa.Column('attempt_date', sa.DateTime(), nullable=False, comment='Attempt timestamp'),
    sa.Column('correct_answers', sa.Integer(), nullable=False, comment='Count of correct answers'),
    sa.Column('total_answers', sa.Integer(), nullable=False, comment='Count of total answers'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='User feedback'),
    sa.ForeignKeyConstraint(['id_quiz'], ['quiz.id_quiz'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_quiz_attempt')
    )
    op.create_index(op.f('ix_quiz_attempt_id_quiz'), 'quiz_attempt', ['id_quiz'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_id_quiz_attempt'), 'quiz_attempt', ['id_quiz_attempt'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_id_user'), 'quiz_attempt', ['id_user'], unique=False)
    op.create_table('answer_option',
    sa.Column('id_answer_option', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('id_question', sa.Integer(), nullable=False, comment='FK → Question'),
    sa.Column('text', sa.Text(), nullable=False, comment='Option text'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='Correct option flag'),
    sa.ForeignKeyConstraint(['id_question'], ['question.id_question'], ),
    sa.PrimaryKeyConstraint('id_answer_option')
    )
    op.create_index(op.f('ix_answer_option_id_answer_option'), 'answer_option', ['id_answer_option'], unique=False)
    op.create_index(op.f('ix_answer_option_id_question'), 'answer_option', ['id_question'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_option_id_question'), table_name='answer_option')
    op.drop_index(op.f('ix_answer_option_id_answer_option'), table_name='answer_option')
    op.drop_table('answer_option')
    op.drop_index(op.f('ix_quiz_attempt_id_user'), table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_id_quiz_attempt'), table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_id_quiz'), table_name='quiz_attempt')
    op.drop_table('quiz_attempt')
    op.drop_index(op.f('ix_question_id_quiz'), table_name='question')
    op.drop_index(op.f('ix_question_id_question'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_quiz_id_quiz'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_id_course'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_course_member_id_user'), table_name='course_member')
    op.drop_index(op.f('ix_course_member_id_course_member'), table_name='course_member')
    op.drop_index(op.f('ix_course_member_id_course'), table_name='course_member')
    op.drop_table('course_member')
    op.drop_index(op.f('ix_course_id_user'), table_name='course')
    op.drop_index(op.f('ix_course_id_course'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_user_id_user'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
